language: node_js
node_js:
- '0.12'
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
- "npm install jpm -g"
- "npm install jshint -g"
addons:
  firefox: "46.0"
script:
- "npm test"
- "jshint *.js"
